title: Services

# Create a opt-in/opt-out overwrite for services to include.
# Auto-populate the rest.

options:
  changeTemplate:
    - article
    - blog
    - hub
    - directory
    - contact
    - services
    
tabs:

  page:
    icon: page
    columns:

      sidebar:
        width: 1/4
        sections:

          leader:
            extends: sections/pages/leader
          auto-leader:
            extends: sections/pages/auto-leader
          auto-intro:
            extends: prompts/services/auto-intro
          auto-text:
            extends: prompts/services/auto-text

      main:
        width: 3/4
        sections:

          text:
            extends: sections/pages/text

  knowledge: tabs/knowledge
  files: tabs/files
  seo: seo/page